### ISSUE TITLE
Add a note using enter.

### ISSUE THREAD

**Issue by 1995YogeshSharma** [1995YogeshSharma/Multi-Stop-Watch#13]
Users should be able to add the note by pressing `enter`.

### Steps to regenerate:
- Add a stopwatch.
- Go to notes button.
- Add a note and try to press enter. (enter doesn't add the todo)

**Comment by shubhamgoel415** [comment]
i would like to work on it

**Comment by 22PoojaGaur** [comment]
created pull request #14
