### ISSUE TITLE
start stopwatch in pause mode by default not resume mode

### ISSUE THREAD

**Issue by 1995YogeshSharma** [1995YogeshSharma/Multi-Stop-Watch#17]
**Current Behaviour** 
On clicking `Add stopwatch`, the stopwatch is added and immediately starts running.

**Expected Behaviour**
the stopwatch should wait for user to click on resume to start

**Comment by SirBob01** [comment]
Hi! I'd like to work on this

**Comment by ayushvashist** [comment]
I'd like to work on this too.

**Comment by 1995YogeshSharma** [comment]
closed with #21
